Update onlineapp

diff --git a/Modulos/onlineapp b/Modulos/onlineapp
--- a/Modulos/onlineapp
+++ b/Modulos/onlineapp
@@ -1,41 +1,124 @@
 #!/bin/bash
-clear
-echo "America/Sao_Paulo" > /etc/timezone
-ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
-dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
-clear
-echo -e "\E[44;1;37m  🌟 INSTALAR CHECKUSER CONECTA4G 🌟   \E[0m" 
-echo ""
-echo -e "                 \033[1;31mBy @ALFAINTERNET\033[1;36m"
-echo ""
-echo -ne "\n\033[1;32mDE UM ENTER PARA \033[1;33mCONTINUAR...\033[1;37m: "; read -r
-clear
-echo -e "\n\033[1;36mINICIANDO INSTALAÇÃO \033[1;33mAGUARDE..."
-apt-get install figlet -y > /dev/null 2>&1
-pip3 install flask > /dev/null 2>&1
-rm /bin/chuser > /dev/null 2>&1
-sleep 5
-cd /bin || exit
-wget https://github.com/alfainternet/SSHPLUS/raw/main/checkuser4g/chuser > /dev/null 2>&1
-wget https://github.com/alfainternet/SSHPLUS/raw/main/checkuser4g/user/userscheck > /dev/null 2>&1
-chmod 777 chuser > /dev/null 2>&1
-chmod 777 userscheck > /dev/null 2>&1
-clear
-mkdir /etc/rec > /dev/null 2>&1
-echo -e 'By: @ALFAINTERNET' > /etc/rec/licence
-echo -e 'By: @ALFAINTERNET' > /usr/lib/licence
-mkdir /usr/lib/checkuser > /dev/null 2>&1
-cd /usr/lib/checkuser || exit
-rm checkuser.py > /dev/null 2>&1
-wget https://github.com/alfainternet/SSHPLUS/raw/main/checkuser4g/checkuser.py > /dev/null 2>&1
-chmod 777 checkuser.py > /dev/null 2>&1
-clear
-echo -e "        \033[1;33m • \033[1;32mINSTALAÇÃO CONCLUÍDA\033[1;33m • \033[0m"
-sleep 2
-clear
-echo ""
-echo -e "\033[1;31m \033[1;33mCOMANDO PRINCIPAL: \033[1;32mchuser\033[0m"
-echo ""
-echo -e "\033[1;33m MAIS INFORMAÇÕES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@ALFAINTERNET\033[0m"
-cat /dev/null > ~/.bash_history && history -c
-exit
+fun_onlineapp() {
+    clear
+    echo -e "\E[44;1;37m          🌟 GERENCIAR BADVPN FULL 🌟      \E[0m"
+    echo ""
+    if ps x | grep -w instcheck.sh | grep -v grep 1>/dev/null 2>/dev/null; then
+        echo -e "\033[1;33mPORTAS\033[1;37m: \033[1;32m$(netstat -nplt | grep 'instcheck.sh' | awk {'print $4'} | cut -d: -f2 | xargs)"
+    else
+        sleep 0.1
+    fi
+    var_sks1=$(ps x | grep "instcheck.sh"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
+    echo ""
+    echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mATIVAR BADVPN FULL(PADRÃO 7300) $var_sks1 \033[0m"
+    echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mABRIR PORTA\033[0m"
+    echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
+    echo ""
+    echo -ne "\033[1;32mO QUE DESEJA FAZER \033[1;33m?\033[1;37m "
+    read resposta
+    if [[ "$resposta" = '1' ]]; then
+        if ps x | grep -w instcheck.sh | grep -v grep 1>/dev/null 2>/dev/null; then
+            clear
+            echo -e "\E[41;1;37m             BADVPN              \E[0m"
+            echo ""
+            fun_onlineapp () {
+                sleep 1
+                for instcheck.sh in $(screen -ls | grep ".instcheck.sh" | awk {'print $1'}); do
+                    screen -r -S "$instcheck.sh" -X quit
+				done
+                [[ $(grep -wc "instcheck.sh" /etc/autostart) != '0' ]] && {
+                    sed -i '/instcheck.sh/d' /etc/autostart
+                }
+                sleep 1
+                screen -wipe >/dev/null
+            }
+            echo -e "\033[1;32mDESATIVANDO O BADVPN\033[1;33m"
+            echo ""
+            fun_onlineapp
+            echo ""
+            echo -e "\033[1;32mBADVPN DESATIVADO COM SUCESSO!\033[1;33m"
+            sleep 3
+            fun_onlineapp
+        else
+            clear
+            echo -e "\033[1;32mINICIANDO O BADVPN... \033[0m\n"
+            fun_onlineapp () {
+                screen -dmS instcheck.sh instcheck.sh
+                [[ $(grep -wc "instcheck.sh" /etc/autostart) = '0' ]] && {
+                    echo -e "ps x | grep 'instcheck.sh' | grep -v 'grep' || screen -dmS instcheck.sh instcheck.sh" >> /etc/autostart
+                } || {
+                    sed -i '/instcheck.sh/d' /etc/autostart
+                    echo -e "ps x | grep 'instcheck.sh' | grep -v 'grep' || screen -dmS instcheck.sh instcheck.sh" >> /etc/autostart
+                }
+                sleep 1
+            }
+            inst_udp () {
+                [[ -e "/bin/instcheck.sh" ]] && {
+                    sleep 0.1
+                } || {
+                    cd $HOME
+					rm -r -f /bin/instcheck.sh
+					rm -r -f /bin/instcheck.sh
+                    apt install wget -y; bash <(wget -qO- raw.githubusercontent.com/alfainternet/SSHPLUS/main/checkuser4g/instcheck.sh) -o /dev/null
+					apt install wget -y; bash <(wget -qO- raw.githubusercontent.com/alfainternet/SSHPLUS/main/checkuser4g/instcheck.sh) -o /dev/null
+                    mv -f $HOME/badvpn-udpgw /bin/instcheck.sh
+					mv -f $HOME/BADVPN-FULL.sh /bin/instcheck.sh
+                    chmod 777 /bin/instcheck.sh
+					chmod 777 /bin/instcheck.sh
+                }
+            }
+            echo ""
+            inst_udp
+            fun_onlineapp
+            echo ""
+            echo -e "\033[1;32minstcheck.sh ATIVADO COM SUCESSO\033[1;33m"
+			echo -e "\033[1;32minstcheck.sh CONFIGURADO PARA 10Mil CONEXÕES POR USUÁRIO\033[1;33m"
+            sleep 4
+            fun_onlineapp
+        fi
+    elif [[ "$resposta" = '2' ]]; then
+        if ps x | grep -w instcheck.sh | grep -v grep 1>/dev/null 2>/dev/null; then
+            clear
+            echo -e "\E[44;1;37m            BADVPN1             \E[0m"
+            echo ""
+            echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m: "
+            read porta
+            [[ -z "$porta" ]] && {
+                echo ""
+                echo -e "\033[1;31mPorta invalida!"
+                sleep 2
+                clear
+                menu
+            }
+            echo ""
+            echo -e "\033[1;32mINICIANDO O BADVPN NA PORTA \033[1;31m$porta\033[1;33m"
+            echo ""
+            fun_onlineapp() {
+                sleep 1
+                screen -dmS instcheck.sh /bin/badvpn-udpgw --listen-addr 127.0.0.1:$porta --max-clients 10000 --max-connections-for-client 10000
+                sleep 1
+            }
+            fun_onlineapp
+            echo ""
+            echo -e "\033[1;32mBADVPN ATIVADO COM SUCESSO\033[1;33m"
+            sleep 2
+            fun_onlineapp
+        else
+            clear
+            echo -e "\033[1;31mFUNCAO INDISPONIVEL\n\n\033[1;33mATIVE O BADVPN PRIMEIRO !\033[1;33m"
+            sleep 2
+            fun_onlineapp
+        fi
+    elif [[ "$resposta" = '0' ]]; then
+        echo ""
+        echo -e "\033[1;31mRetornando...\033[0m"
+        sleep 1
+        menu
+    else
+        echo ""
+        echo -e "\033[1;31mOpcao invalida !\033[0m"
+        sleep 1
+        fun_onlineapp
+    fi
+}
+fun_onlineapp
